// Posts
export const LOAD_POSTS_REQUEST = 'LOAD_POSTS_REQUEST'
export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS'
export const LOAD_POSTS_FAILURE = 'LOAD_POSTS_FAILURE'

// Single Post
export const LOAD_POST_REQUEST = 'LOAD_POST_REQUEST'
export const LOAD_POST_SUCCESS = 'LOAD_POST_SUCCESS'
export const LOAD_POST_FAILURE = 'LOAD_POST_FAILURE'

// Submissions
export const LOAD_SUBMISSIONS_REQUEST = 'LOAD_SUBMISSIONS_REQUEST'
export const LOAD_SUBMISSIONS_SUCCESS = 'LOAD_SUBMISSIONS_SUCCESS'
export const LOAD_SUBMISSIONS_FAILURE = 'LOAD_SUBMISSIONS_FAILURE'

// Single Submission
export const LOAD_SUBMISSION_REQUEST = 'LOAD_SUBMISSION_REQUEST'
export const LOAD_SUBMISSION_SUCCESS = 'LOAD_SUBMISSION_SUCCESS'
export const LOAD_SUBMISSION_FAILURE = 'LOAD_SUBMISSION_FAILURE'
